services:
  - type: web
    name: bank-africa-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: bank-africa-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: bankafrica-db
          property: connectionString

databases:
  - name: bankafrica-db
    databaseName: bankafricadb
    user: bankafricauser
