# Generated by Django 5.2.3 on 2025-06-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="id_document",
            field=models.FileField(blank=True, null=True, upload_to="id_documents/"),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
